name: Go

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'  
    - name: Give permission for make.sh
      run: chmod +x make.sh
    - name: make bin dir
      run: mkdir ./bin/static/
    - name: Test and build
      run: ./make.sh
